services:
  - type: web
    name: trail-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python init_db.py"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
